/**
 * AI Proposal copy generator.
 *
 * Claude writes the narrative sections (intro letter, scope summary, why-us,
 * process, terms) from the structured scope + estimate. Pricing itself is
 * NEVER generated by the model — line items and totals come verbatim from the
 * deterministic estimate, so the numbers the homeowner signs are auditable.
 */
import { anthropic, MODELS } from "./anthropic";
import type { Brandkit, Estimate, Lead, ProjectScope, Tenant } from "@/db/schema";

export interface ProposalContent {
  intro: string;
  scopeSummary: string;
  whyUs: string;
  processSteps: Array<{ title: string; description: string }>;
  terms: string;
}

const SYSTEM_PROMPT = `You are an expert proposal writer for home renovation contractors. You write warm, confident, professional proposals that preserve the homeowner's buying momentum and close deals.

Output ONLY valid JSON matching this exact shape (no markdown, no commentary):
{
  "intro": "2-3 sentence personal letter to the homeowner, referencing their specific project",
  "scopeSummary": "1 short paragraph describing the work in plain homeowner language",
  "whyUs": "1 short paragraph on why this contractor is the right choice",
  "processSteps": [{"title": "...", "description": "1 sentence"}],
  "terms": "2-3 sentences: estimate validity, deposit secures the project slot, final pricing confirmed after on-site measurement"
}

Rules:
- 4-5 process steps from deposit to completion.
- NEVER state any prices, dollar amounts, or percentages — pricing is shown separately from an audited estimate.
- NEVER invent credentials, awards, or guarantees not given to you.
- Warm and personal, not salesy. Write to one homeowner, not a mailing list.`;

export async function generateProposalContent(opts: {
  tenant: Tenant;
  brandkit: Brandkit | null;
  lead: Lead;
  scope: ProjectScope;
  estimate: Estimate;
}): Promise<ProposalContent> {
  const { tenant, brandkit, lead, scope, estimate } = opts;

  const dims = scope.dimensions
    ? Object.entries(scope.dimensions)
        .map(([k, v]) => `${k}: ${v}`)
        .join(", ")
    : "not specified";
  const mats = scope.materials
    ? Object.entries(scope.materials)
        .map(([k, v]) => `${k}: ${v}`)
        .join(", ")
    : "not specified";
  const lineItems = estimate.lineItems.map((li) => li.label).join("; ");

  const res = await anthropic().messages.create({
    model: MODELS.primary,
    max_tokens: 1536,
    system: [
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      { type: "text", text: SYSTEM_PROMPT, cache_control: { type: "ephemeral" } as any },
    ],
    messages: [
      {
        role: "user",
        content: `Write a proposal for:
Business: ${tenant.name}
Specialty: ${tenant.primaryVertical.replace(/_/g, " ")}
Homeowner: ${lead.fullName ?? "the homeowner"}
Project type: ${scope.vertical.replace(/_/g, " ")}
Dimensions: ${dims}
Materials: ${mats}
Timeline: ${scope.timeline ?? "flexible"}
Work covered (no prices): ${lineItems || "full project scope"}
${brandkit?.contractorBio ? `About the contractor: ${brandkit.contractorBio}` : ""}
${brandkit?.voice?.tone ? `Brand voice: ${brandkit.voice.tone}` : ""}`,
      },
    ],
  });

  const text = res.content.flatMap((b) => (b.type === "text" ? [b.text] : [])).join("");
  const jsonText = text.replace(/^```json\s*/i, "").replace(/```\s*$/, "").trim();
  return JSON.parse(jsonText) as ProposalContent;
}

/**
 * Default deposit: 10% of the estimate midpoint, minimum $500,
 * rounded to the nearest $50. Deterministic — no LLM involvement.
 */
export function defaultDepositCents(estimate: Pick<Estimate, "lowCents" | "highCents">): number {
  const midpoint = (estimate.lowCents + estimate.highCents) / 2;
  const tenPercent = Math.round(midpoint * 0.1);
  const floored = Math.max(tenPercent, 50_000);
  return Math.round(floored / 5_000) * 5_000;
}

export function proposalTitle(scope: Pick<ProjectScope, "vertical">, tenantName: string): string {
  const project = scope.vertical.replace(/_/g, " ");
  return `${project.charAt(0).toUpperCase()}${project.slice(1)} proposal — ${tenantName}`;
}
